// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xplcvuswnpxwrmcxpwee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwbGN2dXN3bnB4d3JtY3hwd2VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODY1MzYsImV4cCI6MjA2NTQ2MjUzNn0.T4rfZmKSPjIZc6b4BcZ_yOPtG_ar-OdcNYOoU65F-nU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);